before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew install redis  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then redis-server --daemonize yes ; fi
  
language: node_js

sudo: false

addons:
    code_climate:
        repo_token: 314c0020222b431c924559c453a85c248ee324d91c8746a154399e97367940a7
    codecov:
        token: 1f89ebf3-c7d2-4b18-8136-fe0943a1741d

branches:
  only:
    - master

node_js:
  - '4'
  - '5'
  - '6'
  - '7'
os:
  - linux
  - osx

services:
  - mongodb
  - redis-server
  - docker
  
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules
  
before_script:
  - #npm install -g gulp
  - #npm install -g grunt-cli
  - #npm install -g bower
  - #echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - #bower install -f  
  
after_success:
  - npm run coverage
  - npm install codecov
  - bash <(curl -s https://codecov.io/bash)
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info  
  - #npm run coveralls
